### ISSUE TITLE
Have access to the asking page from home page

### ISSUE THREAD

**Issue by tongweiz** [Alex44711/SOEN-341-UB3#18]
By clicking on ASK A QUESTION button on the HOME PAGE and it will bring you to the ASK PAGE. 

Tasks: Create a button on home page that redirects to the asking page.
Points: 2
Risks: None.
Priority: Important.

**Comment by irinafrazao** [comment]
I just looked at the code that was pushed for this and we will need to fix it to complete this task. It is bad practice to link a page with "localhost:8000/ask" because it implies that the system will always be hosted on your machine. The routes must be used. For an example, look at the logic button in the header that links to the login page.
